### ISSUE TITLE
Error when instzlled with the git and pip

### ISSUE THREAD

**Issue by Tintouin** [i3-workspace-names-daemon/i3-workspace-names-daemon#1]
Traceback (most recent call last):
  File "/usr/bin/i3-workspace-names-daemon", line 33, in <module>
    sys.exit(load_entry_point('i3-workspace-names-daemon', 'console_scripts', 'i3-workspace-names-daemon')())
TypeError: main() missing 1 required positional argument: 'argv'

**Comment by cflewis** [comment]
I get the same thing :(
