### ISSUE TITLE
Pro Icons not available in `fa_icons.py`

### ISSUE THREAD

**Issue by FloydOtsoko** [i3-workspace-names-daemon/i3-workspace-names-daemon#27]
I have recently discovered, that the `fa_icons.py` file is only containing the mappings for the free icons. Therefore people owning the pro version cannot make use of the pro icons, even if they have manually installed them.

[This Line](https://github.com/i3-workspace-names-daemon/i3-workspace-names-daemon/blob/c9ee2f2522dc3a59e7d8898f770858454c1142d7/i3_workspace_names_daemon.py#L378) will only import free icons, when generating a new `fa_icons.py` file.

Having mappings for pro icons in the file, while only having free icons installed, will not do any harm.

therefore I propose to remove this line, and update the icon file

**Comment by CastixGitHub** [comment]
ping @myh2910

**Comment by myh2910** [comment]
Seems fine to remove the line. The metadata of the free version only has free icons, so the line is useless anyway.
