### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by CastixGitHub** [i3-workspace-names-daemon/i3-workspace-names-daemon#6]
any volunteer?

**Comment by FloydOtsoko** [comment]
I am currently playing around with creating a debian package and I will come back to you after I succeeded or gave up

**Comment by FloydOtsoko** [comment]
I created a .deb package which is depended on python3 and python3-i3ipc. It is installable via dpkg. I am not really familiar with going through the process required to have it available via PPA. Should I create a pull request with the deb pack included or how do you suggest handling it?

**Comment by CastixGitHub** [comment]
@FloydOtsoko I've added you as mantainer of a new repo https://github.com/i3-workspace-names-daemon/deb

instead of setting up a PPA just for one packet, for the release phase,
you can use github workflows to build and release the final deb

Thanks

**Comment by FloydOtsoko** [comment]
@CastixGitHub Took some time. But I believe I have found a way which does not require a new repository(?)

I have managed to create a workflow which creates the deb package and create a release in my fork.
I have filed a pull request.
