### ISSUE TITLE
Regolith2 Support

### ISSUE THREAD

**Issue by FloydOtsoko** [i3-workspace-names-daemon/i3-workspace-names-daemon#7]
On Regolith2, the folder for i3 config was moved to `~/.config/regolith2/i3`

Please consider adding this change, or give me the rights in this repo, to create a pull request.

Thanks a lot!

**Comment by CastixGitHub** [comment]
hi, add it [here](https://github.com/i3-workspace-names-daemon/i3-workspace-names-daemon/blob/master/i3_workspace_names_daemon.py#L12) then

**Comment by FloydOtsoko** [comment]
Nice. Thanks. I did.
